# Use the official MySQL image from the Docker Hub
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=employee

# Copy the SQL file into the Docker image
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the port MySQL will run on
EXPOSE 3306
